openapi: 3.0.0
info:
  title: Products Service API
  description: Products Service API
  version: 1.0.0
servers:
  - url: https://29rmxjt9qf.execute-api.eu-west-1.amazonaws.com/prod/

paths:
  /products:
    get:
      summary: Get products list 
      responses:
        '200':
          description: Get products list 
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    price:
                      type: number

  /products/{id}:
    get:
      summary: Get product by Id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Get product by Id
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  price:
                    type: number
        '404':
          description: Product not found

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        price:
          type: number